build:
  nodes:
    analysis:
      project_setup:
        override: ['true']
      tests:
        override: ['php-scrutinizer-run']
      environment:
          php: '7.2'
    craft-tests:
      tests:
        override:
          -
              command: 'vendor/bin/phpunit --coverage-clover=coverage.clover'
              coverage:
                  file: 'coverage.clover'
                  format: 'clover'
      environment:
          php: '7.2'

checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - Tests/*
        - Examples/*
        - Documentation/*